### ISSUE TITLE
Question: location for compiled libraries

### ISSUE THREAD

**Issue by acmertz** [Microsoft/FFmpegInterop#10]
I've successfully compiled FFmpeg for Windows 10 x86 and x64 via the compilation guide for WinRT, but I can't seem to figure out where to put the compiled library so I can actually build the FFmpegInterop project (VS 2015 spits out a lot of errors along the lines of "Cannot open include file: 'libavformat/avformat.h': No such file or directory").

Here's where I currently have FFmpeg:
```
FFmpegInterop\FFmpegSample\FFmpegInterop\Win10\FFmpeg\Build\
```
Inside of that Build directory at the end of the above path are the following directories (each copied directly from the Build directory generated during the compilation process):
```
Win32
x64
```
I'm relatively new to Windows development and library compilation, so I'm sure this is just a simple matter of placing the compiled library in the right place (and making sure its directories are named appropriately). I didn't find anything in this repo's readme, the compilation instructions, or the Windows blog post about it. I have done some Windows app development in the past (Windows 8.x, and now Windows 10) with HTML/JS, but haven't messed around much with WinRT components until now.

Any guidance would be appreciated! Unless I've somehow missed it in all my reading, this might be something worth adding to the readme.

**Comment by MeSaNei** [comment]
Hi,

You should check the ffmpeginterop project settings and look at compiler and linker settings. There will be a relative (to SolutionDir) path. I had to remove one "../"(back directory).

I'm writing from phone. Sorry for any typo.

-----Исходное сообщение-----
От: "Aaron Mertzenich" <notifications@github.com>
Отправлено: ‎14.‎06.‎2015 3:43
Кому: "Microsoft/FFmpegInterop" <FFmpegInterop@noreply.github.com>
Тема: [FFmpegInterop] Question: location for compiled libraries (#10)

I've successfully compiled FFmpeg for Windows 10 x86 and x64 via the compilation guide for WinRT, but I can't seem to figure out where to put the compiled library so I can actually build the FFmpegInterop project (VS 2015 spits out a lot of errors along the lines of "Cannot open include file: 'libavformat/avformat.h': No such file or directory").
Here's where I currently have FFmpeg:
FFmpegInterop\FFmpegSample\FFmpegInterop\Win10\FFmpeg\Build\
Inside of that Build directory at the end of the above path are the following directories (each copied directly from the Build directory generated during the compilation process):
Win32
x64
I'm relatively new to Windows development and library compilation, so I'm sure this is just a simple matter of placing the compiled library in the right place (and making sure its directories are named appropriately). I didn't find anything in this repo's readme, the compilation instructions, or the Windows blog post about it. I have done some Windows app development in the past (Windows 8.x, and now Windows 10) with HTML/JS, but haven't messed around much with WinRT components until now.
Any guidance would be appreciated! Unless I've somehow missed it in all my reading, this might be something worth adding to the readme.

**Comment by acmertz** [comment]
Thanks for the help -- this fixed the problem. I had inadvertently included an extra backslash after $(SolutionDir), which was incorrectly resolved when VS parsed out the macro. Everything is now building properly for me.
