### ISSUE TITLE
Can't use FFmpegInterop.Windows.dll on my Windows Store App project

### ISSUE THREAD

**Issue by enarmedia** [Microsoft/FFmpegInterop#11]
Hello,

I downloaded this project example and when I start the testing MediaPlayerCS sample everything goes fine and I can launch the app. MediaElement player works well with MKV files.

I have developed another app for Windows 8.1 which uses MediaElement and when I try to import the FFmpegInterop.Windows.dll an alert is raised about "this dll is not a valid assembly or COM component". I tried to import the .wimd file of the example and it seemed to correctly load, Intellisense allows me to to call methods on FFmpegInteropMSS object but when launching the app and trying to play the same MKV file Visual Studio 2013 Community Update 4 crashed saying that FFmpeg is not registered (exception when calling method FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri). Probably I am missing some step to properly load and use FFmpegInterop on my project.

I am stuck at this point and can't find a solution, hope you could help me.

Many thanks

**Comment by timotiusmargo** [comment]
Hi there,

You may have missed the FFmpegInterop.dll as implementation of you winmd when you import it. Typically the app build may generate a warning as follows:

warning APPX1707: No implementation file was provided for the .winmd file 'D:\FFmpegInterop\FFmpegSample\Debug\FFmpegInterop.Windows\FFmpegInterop.winmd'. To generate registration information in the app manifest, specify the 'Implementation' metadata on the .winmd reference item in the project file.

You can simply add the dll name under the Implementation property in Reference node of the csproj. E.g.

<Reference Include="FFmpegInterop">
    <HintPath>..\..\..\FFmpegSample\Debug\FFmpegInterop.Windows\FFmpegInterop.winmd</HintPath>
    <IsWinMDFile>true</IsWinMDFile
    <Implementation>FFmpegInterop.Windows.dll</Implementation>
</Reference>

In addition, you need to include all dll (avcodec-56.dll, avdevice-56.dll etc) in your project so that it will be deployed and available in the runtime.

Instead of including FFmpegInterop as reference, you can reference it as a project which does not require adding Implementation node as shown above. Could you give it a try and see how it goes?

**Comment by enarmedia** [comment]
Can't get it to work, I added Reference to Winmd project of FFmpegInterop but no luck, still saying that Requested Windows Runtime type 'FFmpegInterop.FFmpegInteropMSS' is not registered. I tried to manually add <extension> to AppXManifest but no luck. If I try to add just FFmpegInterop.Windows.dll continues saying it is not valid dll. Exception is always raised here: FFmpegMSS = FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri

Would it just be possible for you guys to encapsulate FFmpeg into a one single loadable dll that reads necessary additional dlls from Bin folder and that's it?, No way to use this thing outside this example project... What about creating a NuGet package so we can import into our apps?

I am really interested on this project, it is great but getting too much problems to just get it working on my app.

Any suggestions?

**Comment by enarmedia** [comment]
Finally we achieved to build and create the App package but Windows Certification Kit fails:


Binary analyzer

•Error Found: The binary analyzer test detected the following errors:◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\avcodec-56.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\avdevice-56.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\avfilter-5.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\avformat-56.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\avutil-54.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\swresample-1.dll has failed the AppContainerCheck check.
◦File C:\Program Files\WindowsApps\53877.CloudMediaPlayer_2.0.0.23_x64__dj7px2dfhznsy\swscale-3.dll has failed the AppContainerCheck check.


•Impact if not fixed: If the app doesn’t use the available Windows protections, it can increase the vulnerability of the customer's computer to malware.


•How to fix: Apply the required linker options - SAFESEH, DYNAMICBASE, NXCOMPAT, and APPCONTAINER - when you link the app. See links below for more information:


Supported APIs

•Error Found: The supported APIs test detected the following errors:◦API GetTickCount in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API InitializeCriticalSection in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API RtlAddFunctionTable in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API RtlCaptureContext in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API RtlVirtualUnwind in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API SetUnhandledExceptionFilter in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API Sleep in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.
◦API TerminateProcess in kernel32.dll is not supported for this application type. swscale-3.dll calls this API.


Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 


•How to fix:  Review the error messages to identify the API that is not part of the Windows SDK for Windows Store apps. Please note, C++ apps that are built in a debug configuration will fail this test even if it only uses APIs from the Windows SDK for Windows Store apps. See the link below for more information: 

Any ideas?

**Comment by timotiusmargo** [comment]
Can you please rebuild the FFmpeg libraries (those dll) with -APPCONTAINER linker flag as shown in the wiki below?
https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT#WindowsStore8.1x86Windows8.1Win32inVisualStudio

In particular you want to make sure that you guard against non Windows Apps API as follows (example from Windows 8.1 Store Apps x86)
```
--extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_PC_APP -D_WIN32_WINNT=0x0603" \
--extra-ldflags="-APPCONTAINER" \
```

If you have followed it and still receive any certification failure, could you please provide the Windows Application Certification Kit version that you use?

By the way, we are working on a new directory structure for FFmpegInterop that will have a git submodule pointing to the latest ffmpeg release. With that in place, we can also provide a script that builds FFmpeg libraries in one click. So hopefully it will make it easier for developer and help avoid missing flags.

**Comment by enarmedia** [comment]
Thanks for the reply

We tried the process to obtain the dlls following your instructions but finally no dlls are generated, maybe some intermediary step is failing and we do not have control over that. We tried to use ffmpeg.org Windows builds but the problem continues.

We are using Windows Certification Kit 3.3

Would you mind to send us your compiled libraries and dlls (arm,x86,x64) so we could check?. Looking forward to resolve this final step ;)

Best Regards

**Comment by timotiusmargo** [comment]
The command logs should show you if there is any build error. If you don't see any error and the header are exported properly, you may miss the --enable-shared flag as described in the wiki above. Without that option, FFmpeg libraries will not be built as dll and you may end up with .a files.

As I replied in another thread, the new `BuildFFmpeg.bat` script can be used to easily build FFmpeg libraries provided you set up your environment and retrieve an FFmpeg snapshot.

**Comment by yodurr** [comment]
At this time we are not going to publish ffmpeg binaries.  We are happy to help diagnose build and certification test issues.

**Comment by sixjac** [comment]
What's wrong with you guys? This FFmpeg  Interop is terrible, choppy playback and constant buffering until it wigs out and jumps right to the end of the video.
