### ISSUE TITLE
Minimize latancy over RTP

### ISSUE THREAD

**Issue by Belunn** [Microsoft/FFmpegInterop#110]
I have a time critical function where I want to watch a rtp stream. I have tried all different option settings that I can think of but I cant manage to get down the latency of the stream. I am able to watch the stream in real time in mplayer using the command "mplayer sdp://[mySDPFile].sdp -benchmark -dr -vo gl_nosw" so it should be possible to get it in real time. Is there some settings in FFMPEGInterop that I am missing? Any suggestion of what should be done in order to get as good live view settings as possible is appreciated!

**Comment by Belunn** [comment]
I used the settings from #116 and now the stream plays with very low latency so this issue can be closed.

**Comment by qian256** [comment]
Hi @Belunn 
I am trying to accept RTP stream using FFmpegInterop on UWP, but is not successful. I start the streaming, saved the SDP file, and then open SDP file using the app. It seems that the UDP packages are not going through. How did you manage to run it?
Any tip is super appreciated. Thanks!

**Comment by Belunn** [comment]
Hi @qian256 

I haven´t tried to use a SDP file in visual studio. I use the adress to the stream directly when I create my FFMpeginteropMSS object. Are you able to stream from the SDP file in for instance mplayer or some other player to make sure there is no firewall issue or similar? 

Most of my code is directly from the example project. To start the streaming I use the following line:
FFmpegMSS = FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri("rtp://192.168.40.90:50004", false, false, ffmpegOptions);

The options are configured as #116 as mentioned above.

I have also had issues with some FFmpeg versions. I don´t use the master branch, the only version I have managed to get working is version 3.2. I actually don´t know why the other versions don´t work. If someone else have knwoledge about this it would be interesting to get an explanation of the difference.

**Comment by qian256** [comment]
Hi @Belunn ,
Thank you for your answer. I also tried direct RTP/UDP/TCP streaming, but the result is that no actual packet is received by the UWP. My guess is that there **is** firewall issue. The same stream can be received by ffplayer.
On UWP, there seem not to be any setting about firewall. How did you get through it?
Thanks!

**Comment by Belunn** [comment]
Hi
I did´nt do nothing about firewall settings. I must confess also that I am definitely no expert on this, I just tried around and got it to work :-). If you can stream on ffplayer it seems to me that there is no firewall issue after all. Do you use ffmpeg branch 3.2 as well?

**Comment by qian256** [comment]
I will try ffmpeg 3.2. Are you streaming to UWP device?
Thanks!

**Comment by Belunn** [comment]
Yes I have an UWP app as well. The master branch version of FFmpeg never showed any video in my app. Only branch 3.2. I have tried to switch to the master branch after I got it to work in branch 3.2 but it still doesn´t work.

**Comment by qian256** [comment]
Could you also tell me what is the format of video you are using, and what RTP streaming application did you use? VLC? ffmpeg? or Gstreamer?
I want to at least see a working version ;) Thanks!

**Comment by Belunn** [comment]
I am watching an IP camera on my network (in my case the camera is connected directly to my computers ethernet port). The camera is broadcasting a stream in MJPEG compression over RTP protocol.

**Comment by qian256** [comment]
I see. Thank you @Belunn
