### ISSUE TITLE
Wav rendering issues

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#112]
I tried plugging in some 32bit WAV files in the ffmpeg media stream source machine, and the sound comes out as if it was "fast forwarding" (like the sampling rate was bigger than necessary). Some of them also seem to generate a lot of white noise, although this might be an outcome of the sampling problem.
Anyone else had this issue? It is easy to reproduce if you convert any file to a WAV 32 bit file using audacity and then hook it up to the media stream source.

**Comment by mcosmin222** [comment]
Actually, there seem to be different problems. WAVs generating white noise seem to be encoded with AV_CODEC_ID_PCM_S24LE (so not really 32 bit WAVs as I originally expected) while WAVs which have double sample rate seem to be encoded with AV_CODEC_ID_PCM_F32LE. In the case of AV_CODEC_ID_PCM_F32LE, dividing the sample rate by 2 seems to fix the issue (yes, they need to be handled differently - apparently), while in the case of AV_CODEC_ID_PCM_S24LE, the solution still eludes me :(

**Comment by khouzam** [comment]
This is most likely the same issue as with WMA pro files. The uncompressed audio sample provider uses the input format for the size of the samples but inserts a 16-bit converter. Can you see if gillesk/fixWMAPro branch works with these files.

This hasn't been merged into master yet.

Tue fix is simply to set the audio sample size that we're praying to the media pipeline as 16bits all the time.

**Comment by mcosmin222** [comment]
Damn, how could I have missed that obvious problem?
Yes, simply changing the bit rate of the audio encoding profile to 16 fixed the issue.

**Comment by khouzam** [comment]
Good, going forward, we should look at keeping the higher encoding when possible and feeding it to the media pipeline.

**Comment by mcosmin222** [comment]
ok now... The issue seems fixed for 24 bit audio, however, there still is a sample rate playback issue with 32 bit WAV (it now plays twice as slow and needs a double sample rate).
