### ISSUE TITLE
Crash on specific RTSP camera stream

### ISSUE THREAD

**Issue by wisien92** [Microsoft/FFmpegInterop#116]
Hi, 

I have a problem with one single camera. It crashes while creating FFmpegInteropMSS object. The problem is that that does not occure always. And it only occures on one camera from 8 I test.

>XXX has exited with code -1073740791 (0xc0000409).

I have defined this option set:

    Windows.Foundation.Collections.PropertySet ffmpegOptions = new Windows.Foundation.Collections.PropertySet();
    ffmpegOptions.Add("rtsp_flags", "prefer_tcp");
    ffmpegOptions.Add("allowed_media_types", "video");
    ffmpegOptions.Add("stimeout", 100000 * 5);
    ffmpegOptions.Add("reorder_queue_size", 1);
    ffmpegOptions.Add("packet-buffering", 0);
    ffmpegOptions.Add("fflags", "nobuffer");
    ffmpegOptions.Add("probesize", 32);

    ffMpegMSS = FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri(url, false, true, ffmpegOptions);
    mediaStreamSource = ffMpegMSS.GetMediaStreamSource();

It looks like it freezes for couple of seconds on CreateFFmpegInteropMSSFromUri and then it crashes with output specified above.

How can I  debug it more thourly? App is WP8.1 tested on Lumia 930.

**Comment by khouzam** [comment]
This error code represents a detected buffer-overrun, this is most likely happening in the native side of FFmpeg/FFmpegInterop. Can you open your project and select Mixed-Mode debugging to see if we can figure out where this is occurring in native code.

**Comment by wisien92** [comment]
@khouzam ok I found it. 

> Unhandled exception at 0x6198619F (msvcr120_app.dll) in Versa WM.exe: Fatal program exit requested.

and it points in file utils.c in line 1186 method _handle_formats(c);_

Here is screenshot
![crash](https://cloud.githubusercontent.com/assets/5711300/22057763/69324c32-dd66-11e6-91a6-feb92692d02e.png)

**Comment by wisien92** [comment]
Different problem but same file on newest master branch:

>Unhandled exception at 0x5FFD619F (msvcr120_app.dll) in Versa WM.exe: Fatal program exit requested.

Should I try newer ffmpeg version (e.g. 3.3 ? right now I use 3.1 like master branch)?

**Comment by wisien92** [comment]
It looks like #143 fixed the issue.

**Comment by khouzam** [comment]
Thank you for confirming. I'm glad that this issue is finally resolved.
