### ISSUE TITLE
Can't manage to get audio files working - Unhandled exception

### ISSUE THREAD

**Issue by klappflapp** [Microsoft/FFmpegInterop#12]
Hi,

I had great results playing MKV H.264 files and other formats using the ffmpegInterop sample, but can't get any audio file to work (mp3, aac, flac...).
I traced everything back to detecting the audio stream and decoder, but everything seems fine.
Also, the **OnStarting** and **OnSampleRequested** events get fired, as we can see in the Debug Output (running on Windows Phone 8.1 Device):

```
GetNextSample
Ignoring unused stream
 - PushPacket
 - PopPacket
GetNextSample
 - PushPacket
 - PopPacket
[...]
GetNextSample
 - PushPacket
 - PopPacket
'MediaPlayer.exe' (Win32): Loaded 'C:\Windows\System32\EN-US\mscorlib.debug.resources.dll'. Module was built without symbols.
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0xE0434352 (parameters: 0x80070057, 0x00000000, 0x00000000, 0x00000000, 0x6E100000).
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0xE0434352 (parameters: 0x80070057, 0x00000000, 0x00000000, 0x00000000, 0x6E100000).
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0xE0434352 (parameters: 0x80070005, 0x00000000, 0x00000000, 0x00000000, 0x6E100000).
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0xE0434352 (parameters: 0x80070005, 0x00000000, 0x00000000, 0x00000000, 0x6E100000).
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0x40080201: WinRT originate error (parameters: 0x80070005, 0x000001D3, 0x031FE140).
First-chance exception at 0x770635FB (KERNELBASE.DLL) in MediaPlayer.exe: 0x40080201: WinRT originate error (parameters: 0x80070005, 0x00000047, 0x031FE478).
Unhandled exception at 0x7732062F (COMBASE.DLL) in MediaPlayer.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x0677D898, 0x00000002).


```
The MediaFailed Event gets fired with the following message: *MF_MEDIA_ENGINE_ERR_DECODE : HRESULT - 0xC00D4E87*
If I had to speculate what the cause is, I would say that the Media Element does have a problem with the ffmpeg-decoded stream, but i wouldn't rule out i just did something wrong.

I hope someone can help me with this issue.

**Comment by khouzam** [comment]
Can you share one of the files that you have tried and fails. It will make it easier to reproduce the issue.

Thanks

**Comment by klappflapp** [comment]
Hi,
I just tried my test files again to ensure I pick the right ones and it works now! (tested mp3, flac, ogg and wav).

It seems the audio service somehow was kind of stuck (WP bug?), because I rebooted my phone serveral days ago and it's working now.
Regardless, I guess the problem was not on the interop lib side, so everything is fine now.
