### ISSUE TITLE
Using FFmpegInterop with StreamingRandomAccessStream

### ISSUE THREAD

**Issue by WilliamABradley** [Microsoft/FFmpegInterop#131]
Hi there,
I am currently working on a project that will Stream Video files to an App, from a server that requires an Authentication Header to fetch the file.
Is there a way to get this working with FFmpegInterop?

Currently I am using `StreamingRandomAccessStream` from [This MSDN Blog](https://blogs.msdn.microsoft.com/mcsuksoldev/2014/07/12/video-streaming-with-a-custom-irandomaccessstream-on-windows-and-windows-phone-universal-app/), which works great with the Media Element for Streaming Playback with Authentication, but when passing the stream to the `FFmpegInterop.CreateFFmpegInteropMSSFromStream()` method, it results in an empty Media Element and no buffering, and even freezes the UI.

Is there a solution to get `StreamingRandomAccessStream`s for FFmpeg, or a way to authenticate the `Uri` for `CreateFFmpegInteropMSSFromUri()?`

**Comment by WilliamABradley** [comment]
[FFmpegRandomAccessStream - NoFFmpeg.zip](https://github.com/Microsoft/FFmpegInterop/files/1014344/FFmpegRandomAccessStream.-.NoFFmpeg.zip)

Here is an example of accessing StreamingRandomAccessStream from FFmpegInterop.
I had to remove FFmpeg as it was too big for GitHub, so you will have to source your own, or I could host it on a website with support for larger files.

If you comment out the `Player.SetSource()` at the bottom on MainPage.xaml.cs, and use the `Player.MediaElement.SetSource()` line, it works, as it bypasses FFmpegInterop.

**Comment by khouzam** [comment]
Hi @WilliamABradley,

I finally got around to looking at your repro.

The problem is that FFmpeg does Reads synchronously and this creates a deadlock while the UI thread is waiting for the read to complete that is being performed on the same thread as a work item.

I've modified your FFmpegMediaElement to create the FFmpegInteropMSS on a work thread and playback now works:

```
        public async Task SetSource(IRandomAccessStream stream)
        {
            try
            {
                await Task.Run(() =>
                {
                    // Instantiate FFmpegInteropMSS using the opened local file stream
                    _ffmpeg = FFmpegInteropMSS.CreateFFmpegInteropMSSFromStream(stream, false, false);
                    PlaybackSource = _ffmpeg.GetMediaStreamSource();

                    if (PlaybackSource != null)
                    {
                        MediaElement.Dispatcher.RunAsync(Windows.UI.Core.CoreDispatcherPriority.Normal,
                            () =>
                            {
                                // Pass MediaStreamSource to Media Element
                                MediaElement.SetMediaStreamSource(PlaybackSource);
                            }
                            );
                    }

                    else
                    {
                        Alert("Cannot open media");
                    }
                });
            }
            catch (Exception ex)
            {
                Alert(ex.Message);
            }
        }
```

**Comment by WilliamABradley** [comment]
That's awesome!
Thanks for this.
