### ISSUE TITLE
RTP with sdp file fails

### ISSUE THREAD

**Issue by qian256** [Microsoft/FFmpegInterop#133]
Hi,
Thanks for the great work!
I am trying to setup RTP receiver using your sample. I start RTP streamer using FFmpeg on PC, created SDP file. If I use ffplay to load the SDP file, it is working fine. If I load the SDP file in the sample app, it does not get any packet. I found out that it is a connection issue.
Basically, UDP packet is not received by the client. Is that common?
Thanks again!

**Comment by qian256** [comment]
Well, it works now.

**Comment by pixelivore** [comment]
Hi qian256,
I think i'm facing the same problem.
I'm trying to build an UWP app to receive a rtp stream (using a sdp file).
I don't seem to receive anything, even if all functions don't send any error.
I know it's been a year now, but do you remember what you did to resolve your problem?
Thanks
