### ISSUE TITLE
real time playback issues

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#134]
I decided to go ahead and try real time playback on both a MediaPlayer and a MediaElement object. Sounds stutters, is chopped or even pauses sometimes. Like 90% of the time it plays correctly, but then there's occasional chops, stutters and even pauses (like the media stream source can't provide the samples fast enough).

Is there something that I need to alter in order for this to work properly with realtime playback?

**Comment by Belunn** [comment]
For me the option settings suggested in #116 works well to get a good real time playback for a network camera stream. But I don´t know if theese options can be used in your case as well.

**Comment by mcosmin222** [comment]
I use audio files for playback. So not really related but i can look over that.

**Comment by mcosmin222** [comment]
Sadly, those settings have no effect.
