### ISSUE TITLE
RTSP support?

### ISSUE THREAD

**Issue by wisien92** [Microsoft/FFmpegInterop#14]
Is there RTSP support ? I found this link and it doesn't work:
rtsp://media1.law.harvard.edu/Media/policy_a/2012/02/02_unger.mov

And another question - do you have any live video links that I can test? The only video I got to work was rabbit trailer.

**Comment by timotiusmargo** [comment]
Hi there,

The link you provided above returned HTTP 404 NOT Found. I have verified the same error with other RTSP stream players as well.

I used the links enlisted in 
http://g33ktricks.blogspot.com/p/the-rtsp-real-time-streaming-protocol.html to test FFmpegInterop RTSP streaming

**Comment by wisien92** [comment]
Right now the video is down it's true, but 3 months ago when I was trying out this library It was not playing but using other libs on Android an IOs it worked.

Thanks for links I will come back to testing soon.
