### ISSUE TITLE
Memory leak in ffmpeg AVUTIL-55

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/FFmpegInterop#142]
I found a memory leak which traces back to AVUTIL-55.
Can anyone confirm this?

![avutil leak](https://user-images.githubusercontent.com/9284164/26850122-2079c99a-4b0f-11e7-8189-81d3ea7db1ac.PNG)

**Comment by khouzam** [comment]
Hi @mcosmin222

**Comment by mcosmin222** [comment]
Yes, this is simply by playing back things (with force audio decode). I managed to reproduce it with the FFMPEG.interop nuget package as well.

You can try the sample bellow. Start it and watch in task manager as memory slowly builds up (roughly 0.1 MB every 3 seconds).

[MediaPlayerCS.zip](https://github.com/Microsoft/FFmpegInterop/files/1057009/MediaPlayerCS.zip)

**Comment by mcosmin222** [comment]
The problem seems to be somewhere along the path of decoding audio files. There is no leak if we don't force decoding.

**Comment by khouzam** [comment]
Ok, I found the leak, we were leaking every single sample because I was using `av_freep` instead of `av_sample_free` to free them. The profiler in VS did find the samples and showed that there were about 1800 more allocations in a 30 second period and most of them were from `av_sample_alloc`.

**Comment by khouzam** [comment]
@mcosmin222 can you try the fix and confirm that the leak is gone in your case?

**Comment by mcosmin222** [comment]
Hmm I think we might leak packages as well.
After merging your changes, I get the following leak:

![capture 22](https://user-images.githubusercontent.com/9284164/26944682-0d6fb272-4c92-11e7-87e1-438de93758a2.PNG)

Can you check and see if you have the same problem? Maybe I didn't merge properly.

**Comment by mcosmin222** [comment]
Ok ignore that. Ive run a stress test for a few hours and app remained stable. All seems good, if I can find something else I will post here.

**Comment by khouzam** [comment]
After confirmation I've merged the fix.
