### ISSUE TITLE
Getting crash on some desktops with sws_getContext

### ISSUE THREAD

**Issue by mcosmin222** [Microsoft/FFmpegInterop#147]
Unhandled exception at 0x760E543B (ucrtbase.dll) : Fatal program exit requested.

The thing is, the very same files work fine on other machines, and there seems to be no obvious difference (both run on windows 10, same build).

	m_pSwsCtx = sws_getContext(
			m_pAvCodecCtx->width,
			m_pAvCodecCtx->height,
			m_pAvCodecCtx->pix_fmt,
			m_pAvCodecCtx->width,
			m_pAvCodecCtx->height,
			AV_PIX_FMT_NV12,
			SWS_BICUBIC,
			NULL,
			NULL,
			NULL);

Somehow, ffmpeg reports pix_fmt as none (-1). I would guess this is the problem. The same file works fine on other players.

**Comment by khouzam** [comment]
Hi @mcosmin222 

Can you create a memory dump of the crash?

**Comment by mcosmin222** [comment]
Hi @khouzam 

I can reproduce the issue with my local copy of ffmpeg interop but can't do it with the nuget package.
It looks like avcodec_open2(avVideoCodecCtx, avVideoCodec, NULL) fails to copy the pix_fmt from avVideoCodec to avVideoCodecCtx.

I will upload a crash dump after I investigate some more.
