### ISSUE TITLE
Build Error in FFmpegInteropMSS.cpp

### ISSUE THREAD

**Issue by naplings** [Microsoft/FFmpegInterop#150]
When I tried to build the project. 
It said:
> Error (active)	E2338	a brace-enclosed list is not allowed here	FFmpegInterop  

in  

[FFmpegInteropMSS.cpp](https://github.com/Microsoft/FFmpegInterop/blob/master/FFmpegInterop/Source/FFmpegInteropMSS.cpp#L451)   Line: 451

```
mss->BufferTime = { 0 };
```

I tried to add ``\std:c++latest`` option in project properties. However, it didn't work.   
Could you please tell me how I can fix this error?  

Thanks for your outstanding work. It helps me a lot 😄 

### Env:
VS2017(*Ver. 15.2(26430.15)*)  
Windows 10 (*Ver. Build 16232*)

**Comment by khouzam** [comment]
Hi @naplings 

Which compiler are you using? Did you modify the project at all?

**Comment by naplings** [comment]
@khouzam 
I used the method in #136 -- the vcpkg to build the ffmpeg.
The complier is the default one in VS2017. I think it is VC++ build version v141.
I haven't modified the project yet.

Maybe I should install the v140 VC++ build tools?

**Comment by khouzam** [comment]
Hi @naplings 

Are you seeing this as a build failure or an intellisense failure? I'm not seeing the build fail, but I do see the error as intellisense.

**Comment by naplings** [comment]
Hi @khouzam 

Thanks for your patience. Today, when I tried to rebuild this project, the error didn't appear anymore. (I upgraded the project target to VC++ v141). It seems like a intellisense failure which prevent  building process.

Thanks again for your reply. 😃
