### ISSUE TITLE
About av_seek_frame()

### ISSUE THREAD

**Issue by naplings** [Microsoft/FFmpegInterop#151]
In [FFmpegInteropMSS.cpp Line 661](https://github.com/Microsoft/FFmpegInterop/blob/master/FFmpegInterop/Source/FFmpegInteropMSS.cpp#L661)
```cpp
if (av_seek_frame(avFormatCtx, streamIndex, seekTarget, 0) < 0)
```
It might be better to change the last parameter to AVSEEK_FLAG_BACKWARD.  
```cpp
if (av_seek_frame(avFormatCtx, streamIndex, seekTarget, AVSEEK_FLAG_BACKWARD) < 0)
```
I tried to make this change in my local project. And the performance of seeking is better than the old one.  
In FFmpeg document, it looks like the AVSEEK_FLAG cannot be 0.  

However, this change cannot solve the problem that some video will stop playing after seeking.  
How can I fix this problem?

Thank you! 😄

**Comment by khouzam** [comment]
Hi @naplings 

Thanks for the suggestion, I'll take a look at it.

For the issue with the videos that stop playing after seeking? This is a Media Foundation issue within MediaStreamSource. It has been fixed in Windows 10 (can't remember the exact release). Where does it repro for you?

**Comment by naplings** [comment]
Hi @khouzam 

Thank you, I'll check this in fast ring insider preview. Thanks again for your excellent work. 😄

**Comment by mcosmin222** [comment]
Is the fact that videos freeze when the phone returns from background the same issue you are referring to?
