### ISSUE TITLE
Background video playback

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#157]
Hello again,

I noticed the following behaviour: if I used this media stream source to play video file in background on a phone and then lock the screen, wait 10-20 seconds then unlock the screen, video playback stops. 

The media stream source continue to request samples but the MediaPlayerElement doesn't render them.
Does anyone have any idea about this?

Technically, starting with AU, Background video playback should be possible but I noticed no other app on windows mobile does so.

**Comment by reego-fr** [comment]
Hi, I had issues too with background video playback on my first experiments with MediaStreamSource api years ago on desktop. I can't remember if I already talked about it here but was not able to find a fix. 
Initially found on 8.1, I remember I was able to reproduce the issue on Windows 10 when minimizing the playing app, maybe only in tablet mode. I would love to see it fixed too !
