### ISSUE TITLE
Dll's to pass Windows Certification

### ISSUE THREAD

**Issue by enarmedia** [Microsoft/FFmpegInterop#16]
Hello everyone,

We have been trying to build dll's following the steps provided by the team but we couldn't get proper working dll's to pass Windows Store Certification.

If anybody achieved this step, please would you mind to send us your dll's (x86,x64) so we can continue our testing project, we are stuck at this step.

Thanks a lot for your great work

**Comment by mcosmin222** [comment]
What error you getting and which platform are you targeting?

**Comment by enarmedia** [comment]
We try to build using these parameters:

--extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_PC_APP -D_WIN32_WINNT=0x0603" \
--extra-ldflags="-APPCONTAINER" \

But no dll's are generated. It seems that some intermediate step of the script is failing and we cannot track the issue. Is there any alternative script to get the dll's

**Comment by timotiusmargo** [comment]
Hi there,

To generate the dll, --enable-shared option needs to be specified when configuring FFmpeg as described in the build instruction below:
https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT

However we understand the necessary build steps can be overwhelming for some and we'd like to make it easier. I just checked in `BuildFFmpeg.bat` script that will perform all the steps in the compilation guide above. If you have installed all the necessary tools as instructed, the script will generate the libraries for you. README.md is updated with some instruction on how to run it in the new directory structure. Could you please give it a try?

**Comment by enarmedia** [comment]
Hello Timotious, thanks for your messages.

I run the script and it compiles, when finished I realise that no Build folder is generated, instead I get an "Output" folder which contains folders for the architectures selected Windows 8.1/x86 x64.

Unfortunately no bin folders are created containing the .lib files and dlls. For example I get error "avcodec.lib" not found. Also I get errors of this type:

Error	1	Cannot find assembly "C:\Users\enarmedia\Downloads\FFmpegInterop-master\FFmpegInterop-master\ffmpeg\Build\Windows8.1\x86\bin\avcodec-56.dll", which may contain managed resources that need to be included in this app package.  Please ensure that this assembly exists.	MediaPlayerCS.Windows

Your script runs but I think the final step to create bin folders with lib and dlls is failing...

Any ideas?, would you mind to send me your Output generated folder so I could compare?

Thanks

**Comment by yodurr** [comment]
Tim to follow up

**Comment by timotiusmargo** [comment]
Hi @enarmedia,

Did you manage to get the libraries generated? Ideally you will want to generate the libraries yourself as you may want to configure it in your specific need. Let us know if there is still thing we can help with.
