### ISSUE TITLE
UWP 14393, mediaplayerelement, http flv streaming or rtmp streaming, video stops as soon as pressing left or right direction key on keyboard

### ISSUE THREAD

**Issue by TaoziDB** [Microsoft/FFmpegInterop#160]
FFmpegInterop [@67a29ba](https://github.com/Microsoft/FFmpegInterop/tree/67a29bab939303caf694d3d813ee18fe5ff717c9)
ffmpeg [@12320c0](https://github.com/FFmpeg/FFmpeg/tree/12320c08221f0eecf6d9af3a6f12f42e656f0674)
UWP 14393, Visual Studio 2017, MediaPlayerElement, playing http flv streaming or rtmp streaming, video plays as normal, but stops as soon as pressing left or right direction key on keyboard.

Another situation is that if no user interruption, the video will automatically stop in about 3 - 5 minutes.

Curiously, this only happens on release mode, if on debug mode, video will not stop when left or right direction key is pressed or in about 3-5 minutes.

Can you point me to the right direction?

I know FFmpeginterop and ffmpeg builds I am using are very old, but I failed to build myself, so I use [https://github.com/zhengbomo/FFmpegInterop](https://github.com/zhengbomo/FFmpegInterop), Nuget 1.04 package

If someone knows this bug existed for old version and newer version of FFmpeginterop and ffmpeg have since fixed this, please let me know, then I guess I need try to build newest version myself again.

[Update] If I enable "Compile with .NET Native tool chain" for debug mode, the same stop bugs will happen, since in release mode, "Compile with .NET Native tool chain" is enabled per windows store requirement, which means "Compile with .NET Native tool chain" is the problem, what to do now?

**Comment by mcosmin222** [comment]
This may be related to #157

**Comment by lukasf** [comment]
@TaoziDB Please make sure you store FFmpegInteropMSS reference in C# during playback, see my comment on #166 .

**Comment by TaoziDB** [comment]
What do you mean "store"? Do you have couple of lines of sample I can look at?

**Comment by lukasf** [comment]
Please check MainPage.xaml.cs in the sample app:

```
    public sealed partial class MainPage : Page
    {
        private FFmpegInteropMSS FFmpegMSS;
        ...
        private async void OpenLocalFile(object sender, RoutedEventArgs e)
        {
	            FFmpegMSS = FFmpegInteropMSS.CreateFFmpegInteropMSSFromStream(readStream, forceDecodeAudio, forceDecodeVideo);

```

The page has a field FFmpegMSS. When a file is opened, the FFmpegInteropMSS object that was created is stored in that field. Because of this, the Garbage Collector cannot delete FFmpegInteropMSS, until the next file is opened.

If you just store ffmpeg in a local variable (like below), it will move out of scope once the method is left, and the object can be GC'd any time.

`var ffmpeg = FFmpegInteropMSS.CreateFFmpegInteropMSSFromStream(readStream, forceDecodeAudio, forceDecodeVideo);`

**Comment by TaoziDB** [comment]
But in my case above, source is local to ViewModel, should not be deleted by GC, right?
Here is the definition of source:

private IMediaPlaybackSource _source;
public IMediaPlaybackSource source
        {
            get { return _source; }
            set
            {
                _source = value;
                OnPropertyChanged("source");
            }
        }

public void OnPropertyChanged(string propertyname)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyname));
        }

**Comment by lukasf** [comment]
Storing the MediaPlaybackSource is not enough. You must also store the FFmpegInteropMSS itself. Otherwise it will be eaten by GC.

**Comment by TaoziDB** [comment]
I understand now, how about mss in my case?

I will test as soon as I get home

**Comment by lukasf** [comment]
MSS does not need to be stored, at least for me, storing FFmpegInteropMSS was sufficient...

**Comment by TaoziDB** [comment]
It works, thanks so much. It seems GC in Release mode is more brutal than GC in Debug mode.

In summary, per  @lukasf [Issue #160 comment](https://github.com/Microsoft/FFmpegInterop/issues/160#issuecomment-334765814) the solution is to store the FFmpegInteropMSS object to avoid GC. DO NOT USE local variable.

**Comment by lukasf** [comment]
You are welcome, glad to hear that it solved the problem for you as well!
