### ISSUE TITLE
a bug and a question.

### ISSUE THREAD

**Issue by cansado2930** [Microsoft/FFmpegInterop#161]
Hello,
I have compiled the last commit of master today and If i play a mp4 video, it is played with 2x or 3x of normal speed. It is played very fast. With mp3 file, it Works correctly. It has been tested with the sample app.
And about question, I'm trying to play rtp over Multicast and it doesn't work. I tested it with ffplay and works so, What should I do in order to play rtp video from Multicast.?
Thanks you

**Comment by touseefbsb** [comment]
I am having the same problem with video files it plays very fast, even the sample app is giving this problem

**Comment by mcosmin222** [comment]
Can you check if the sampling rate detected by the FFMPEG interop is 2x-3x bigger than what other players report?

**Comment by touseefbsb** [comment]
how can we check the sampling rate?

**Comment by mcosmin222** [comment]
In ffmpeg interop you can check the values used to create AudioEncodingProfile or VideoEncodingProfile.

In windows explorer, you can usually see these values in the details tab of a files property window.

**Comment by touseefbsb** [comment]
which file should we check? please clarify as you said we should check sampling rate from ffmpeginterop and also from other players, how should we do that? Thanks

**Comment by touseefbsb** [comment]
I normally checked audio sample rate by right clicking video file in file explorer and going to details tab and value is "24 kHz"

**Comment by cansado2930** [comment]
I have checked values of size, códec, frame rate, channels,... from audio and video and they are same from properties of file.

**Comment by khouzam** [comment]
Do you have a sample that we can look at?

**Comment by cansado2930** [comment]
One of videos that I have test it is this: https://1drv.ms/v/s!Av2l1Q_MdsTVggd2TyPtrQIuRMpG
I have told about 0.5 in order to know the speed of play video. But you can't use 0.5 as normal because the sound is x2x0.5 so it doesn't sound very well.

**Comment by khouzam** [comment]
Thanks. I can repro the issue with the most recent code, but not with an older build so its a recent regression. Let me investigate a little bit more.

**Comment by khouzam** [comment]
I've identified the code change that is causing this. In order to improve performance with small audio samples, we've tried to create bigger samples when they are too small, but it seems that for this file, the concatenation is not fully working.

For the time being, you can change the following line in FFmpegInteropMSS.cpp from 500000 to 0 and this will restore the previous logic:
```
// Minimum duration for audio samples (50 ms)
const TimeSpan MINAUDIOSAMPLEDURATION = { 500000 };
```

**Comment by touseefbsb** [comment]
@khouzam  would this be fixed in the next update of the repo? and for now as you mentioned do we neeed to just change this one line of code? or do we also need to change the playback rate of the media element?

**Comment by khouzam** [comment]
Hi @touseefbsb

Yes, we are looking to fix this issue very soon. For the workaround you just need to change the single value, the playback rate of the MediaElement would not need to be modified.

**Comment by bosxixi** [comment]
how to set 2x play speed? i set the 
```
var options = new PropertySet();
options .Add("filter:v", @"setpts=0.5*PTS");
```
but nothing is working.

**Comment by khouzam** [comment]
Hi @bosxixi,

Please open a new issue with your question as it makes it easier to track.
