### ISSUE TITLE
A lot of warnings when building FFmpeg. The "Build/Windows10/x64" is not there.

### ISSUE THREAD

**Issue by AnisaulM** [Microsoft/FFmpegInterop#162]
I followed what has been told in https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT
Unfortunately, this is I got a lot of warnings when building the FFmpeg from Windows 10 x64. This is the one of the warning that I got when I run the make command:

![image](https://user-images.githubusercontent.com/25203103/29064395-b551e560-7c20-11e7-942f-914911996415.png)

Does it mean the FFmpeg wasn't installed correctly? Please help me...

I'm a newbie in FFmpeg, would someone please explain the solution?

Thanks for your help...

Update: I just realized that I couldn't find Build/Windows10/x64 folder that is supposed to contain all the generated libraries. Please help....

**Comment by khouzam** [comment]
Hi @AnisaulM 

The warnings are part of the FFmpeg build, the warnings are different based on the compiler and they don't necessarily affect the code.

Can you share your log files? They should be in Output/Windows10/x64 if you're following the instructions on the Wiki.

**Comment by AnisaulM** [comment]
Is it this one?

[config.txt](https://github.com/Microsoft/FFmpegInterop/files/1208930/config.txt)

I tried to install it again and I can find the build folder. But there is no ffmpeg.exe.

**Comment by khouzam** [comment]
You will not find ffmpeg.exe building the WinRT/Store version as described in the Wiki page you mention. You will get the FFmpeg libraries (avcodec, avutil,...) This enables you to use FFmpeg in a Universal Windows Application but the command line utilities for FFmpeg do work in that environment. You can still build the windows desktop version if you want the command line utilities and those would still work in Windows 10.

**Comment by AnisaulM** [comment]
Ah, I'm sorry. So, the one that I did was done correctly? I can proceed to the next step which is trying the FFmpeg in Visual Studio, right?

I can use the libraries to be include in some kind of C scripts, right?

**Comment by khouzam** [comment]
Yes, your build looks correct. You can look at this project (FFmpegInterop) to see how to use the libraries in a project.

**Comment by AnisaulM** [comment]
Ok. I will try it with this project then. Thank you very much...
