### ISSUE TITLE
Sample duration issues

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#167]
I encountered a file which ffmpeg reports to have  packages of 0 length (which is wrong since we read buffer from them). I suspect it is so because ffmpeg improperly reports a block align of 0 for that file, when it is in fact 4. I think we should default to doing the mathematical calculation of buffer lengths manually when this particular condition occurs to prevent any possible wide range of bugs in ffmpeg.

I've done it for uncompressed audio sample provider.

The mathematical formulae are

block_align = num_chanels * (bit_rate / 8); bit_rate is always 16 in our case, hence it becomes num_chanel*2;

average_bytes_per_second = sampe_rate * block_align

buffer_duration = buffer_.length/ average_bytes_per_second  * 10000000;

**Comment by khouzam** [comment]
Hi @mcosmin222 

Has this been addressed with #178? Can we close the issue?

**Comment by mcosmin222** [comment]
hi @khouzam 
#178  never got merged. I closed it. You can cherry pick the specific commit which fixes this issue.
