### ISSUE TITLE
Streams are stopped as soon as a single corrupted package occurs

### ISSUE THREAD

**Issue by lukasf** [Microsoft/FFmpegInterop#175]
Especially with broadcast streams, broken packets can occur, but also normal files can have a broken packet here and there (bad encoder, whatever). With the current code, if a packet cannot be decoded, a "null" value is returned as Sample. If MediaStreamSource gets a "null" Sample on a stream, this is always considered end-of-stream, so playback of that stream is stopped for good and will not recover.

I would propose to add an option "BrokenPacketThreshold". If you assign e.g. 10, then this means that up to 10 broken packets can occur in a row before the stream is stopped. Default would be 0 (current behavior), -1 would mean skip all packets until a good one is found.

I have already tested a quick hack of this with partly corrupted mpeg files, works well for me.

**Comment by mcosmin222** [comment]
I have a fix for this. PR latter on.

**Comment by lukasf** [comment]
Cool, looking forward to that.

**Comment by mcosmin222** [comment]
But it is pretty much the same implementation as what you said: it tries to skip over 10 broken packages in a row. if more than 10 then aborts with null sample. So if you already have something, feel free to upload.

**Comment by lukasf** [comment]
There are some more things to consider here: If we return a null sample (because more than X broken packets have been read), we must disable the stream internally. Otherwise, the stream's packet queue will be flooded. Packets are still enqueued by the reader but no samples are read out anymore by MSS so queue grows infinitely.

I will come up with a PR for this soon fixing both problems.

**Comment by lukasf** [comment]
Please check my solution #182.
