### ISSUE TITLE
FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri returns null on x86 Mobile Emulator 10.0.14393.0

### ISSUE THREAD

**Issue by TaoziDB** [Microsoft/FFmpegInterop#177]
FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri returns null on x86 Mobile Emulator 10.0.14393.0
Is this a known bug?

It works on other modes:
x86 PC, x64 PC, x64 XBOX and ARM device

There is no real world x86 mobile device, right?

So store submission should be fine, although no x86 mobile emulator support is really inconvenient :(

**Comment by khouzam** [comment]
No that isn't known. Thanks for raising the issue. But you are correct that there are no x86 mobile device, but the binary is the same as x86 desktop. So it might just be a problem with the emulator, more than with FFmpegInterop.

**Comment by khouzam** [comment]
Hi @TaoziDB,

I've double checked and I'm not reproducing the issue with the 14393 Emulator. I'm running our CreateFromUri_Force_Video test from the UnitTest project which calls 

I'm also trying our MediaPlayerCPP sample with the following URI and it plays normally in the emulator:
rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov

Do you have a link that exhibits the problem? Also which size and build of the emulator are you using? I'm looking at 10.0.14393.0.

Thanks

**Comment by TaoziDB** [comment]
If I remember correctly, 720p 5 inch 1GB.

I will double check when I get home tonight, thanks.

**Comment by TaoziDB** [comment]
Upon further testing, I reinstalled all emulators, now it works, so false alarm, the fault is on my pc and me, not on ffmpeginterop, sorry for wasting your time, issue is now closed
