### ISSUE TITLE
video stops when set position in code behind

### ISSUE THREAD

**Issue by HppZ** [Microsoft/FFmpegInterop#180]
but audio keeps going.
if you need a file that can reproduce this issue, please contact me (haopeng__@outlook.com)

**Comment by touseefbsb** [comment]
@khouzam  How about this issue?

**Comment by khouzam** [comment]
I'm not sure I see the issue.

I've added a click handler with the following code to seek when the button

```
void MediaPlayerCPP::MainPage::ButtonClicked(Platform::Object^ sender, Windows::UI::Xaml::RoutedEventArgs^ e)
{
    Windows::Foundation::TimeSpan span;
    span.Duration = 500000000L;   // convert 1 sec to 100ns ticks

    mediaElement->Position = span;
}
```
This works both with force decode and not.
If you can share repro steps that would be really helpful.

**Comment by HppZ** [comment]
Problem fixed after I updated source code of this repo.
Thanks.
