### ISSUE TITLE
vcpkg branch is 42 commits behind the master

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/FFmpegInterop#181]
vcpkg branch was created so that VS 2017 users can easily build packages for themselves, but it has some bugs like seeking video closes e.t.c, I think those bugs are fixed in latest master branch. but vcpkg branch is 42 commits behind , so please update it to latest branch and keep it updating with the master in future, or just enable vs 2017 building on the master branch

**Comment by khouzam** [comment]
Updated for VS2017.

**Comment by touseefbsb** [comment]
can you please guide me how can I now build for vs 2017? should I use the same method you already described in issue with vs 2017? or should I build with master branch? or should I build with following branch ?
https://github.com/Microsoft/FFmpegInterop/tree/gillesk/vcpkg
