### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by tunerok** [Microsoft/FFmpegInterop#188]
hi! 
I have the same problem. The folder is in the **same directory**. Solution of the problem is still not there.

I did git clone --recursive git://github.com/microsoft/FFmpegInterop.git and build ffmpeg is got error?
`C:\WINDOWS\system32>"C:\Users\sieu nhan gao\FFmpegInterop\BuildFFmpeg.bat" win10
Verifying ffmpeg directory...
The system cannot find the path specified.

configure is not found in ffmpeg folder. Ensure this folder is populated with ffmpeg snapshot`
#101

**Comment by khouzam** [comment]
Hi @tunerok 

Is there a space in the path that you're trying to build?

**Comment by tunerok** [comment]
@khouzam 
Path directory is "C:\FFmpegInterop\BuildFFmpeg.bat". No spaces or "not ASCII"-words. CMD run as administrator(root).

**Comment by khouzam** [comment]
Can you comment out the `@echo off` line in BuildFFmpeg.bat and capture the result?

**Comment by tunerok** [comment]
@khouzam 
No problem. 
![efef](https://user-images.githubusercontent.com/20516589/32629727-3529faba-c5ab-11e7-86a8-9dc1d4098e3e.JPG)

**Comment by khouzam** [comment]
@tunerok,

Can you go into the FFmpegInterop folder and launch the script from there?

I'll update it to change the directory and fix this.

**Comment by khouzam** [comment]
I've pushed the fix, it was trivial.

**Comment by RAKIBUL-RAZU** [comment]
give me solve it!s
