### ISSUE TITLE
FFmpeg fails WACK certification

### ISSUE THREAD

**Issue by psled** [Microsoft/FFmpegInterop#190]
I was able to compile and use successfully both FFmpeg and FFmpegInterop inside my UWP app.

The problem is with creating an Appx package for Store distribution. FFmpeg libraries are failing WACK certification.

**Environment**:

- Windows 10 Version 1709 (Build 16299.19)
- Windows App Certification Kit 10.0.16299.15
- Windows Target Platform Version 10.0.16299.0
- Platform Toolset v141
- FFmpeg branch: master, n3.3.5, n3.3.2
- x64 Native Tools Command Prompt for VS 2017 v15.4.3
- FFmpegInterop branch: master
- Target arch: x64 / bundle
- Configuration: release

**FFmpeg configuration** (as described [here](https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT)):

../../../configure \
--toolchain=msvc \
--disable-programs \
--disable-d3d11va \
--disable-dxva2 \
--arch=x86_64 \
--enable-shared \
--enable-cross-compile \
--target-os=win32 \
--extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00" \
--extra-ldflags="-APPCONTAINER WindowsApp.lib" \
--prefix=../../../Build/Windows10/x64

**Notes**:
Not sure if it's related or not but I have spotted that recent changes in FFmpeg use HAVE_UWP definition.

More on this [here](https://git.ffmpeg.org/gitweb/ffmpeg.git?a=search&h=HEAD&st=commit&s=uwp).

**WACK log** (for FFmpeg branch master, previous releases are different only by lib version number, e.g. avcodec-57.dll instead of avcodec-58.dll):

API __C_specific_handler in vcruntime140.dll is not supported for this application type. swscale-5.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. swscale-5.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. swscale-5.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. swscale-5.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. swscale-5.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. swscale-5.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. swscale-5.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. swscale-5.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. swscale-5.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. swscale-5.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avdevice-58.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avdevice-58.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. avdevice-58.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avdevice-58.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avdevice-58.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avdevice-58.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. avdevice-58.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. avdevice-58.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. avdevice-58.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. swresample-3.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. swresample-3.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. swresample-3.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. swresample-3.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. swresample-3.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. swresample-3.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. swresample-3.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. swresample-3.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. swresample-3.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API memchr in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API strstr in vcruntime140.dll is not supported for this application type. avcodec-58.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avcodec-58.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avcodec-58.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. avcodec-58.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. avcodec-58.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. avcodec-58.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API strrchr in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API strstr in vcruntime140.dll is not supported for this application type. avfilter-7.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avfilter-7.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avfilter-7.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. avfilter-7.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. avfilter-7.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. avfilter-7.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API memchr in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API strrchr in vcruntime140.dll is not supported for this application type. avutil-56.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avutil-56.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avutil-56.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. avutil-56.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. avutil-56.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. avutil-56.dll calls this API.
API __C_specific_handler in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API __std_type_info_destroy_list in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API memchr in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API memcmp in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API memcpy in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API memmove in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API memset in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API strchr in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API strrchr in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API strstr in vcruntime140.dll is not supported for this application type. avformat-58.dll calls this API.
API GetModuleHandleW in kernel32.dll is not supported for this application type. avformat-58.dll calls this API.
API GetStartupInfoW in kernel32.dll is not supported for this application type. avformat-58.dll calls this API.
API RtlCaptureContext in kernel32.dll is not supported for this application type. avformat-58.dll calls this API.
API RtlVirtualUnwind in kernel32.dll is not supported for this application type. avformat-58.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. avformat-58.dll calls this API.

**Comment by khouzam** [comment]
Thanks for reporting the issue.

I'm seeing the same results. I'm wondering if this a v141 toolset issue vs v140. I'll keep looking at this over the next week.

**Comment by khouzam** [comment]
Hi @psled 

I've identified the issue and I'll try to update the wiki instructions for VS2017 to improve the experience.

The problem is with your environment setup, by default using a Developer command prompt will target a desktop build and not a UWP. To target a UWP you should update your environment variables with the following command:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\<Edition>\VC\Auxiliary\Build\vsvarsall.bat x64 store`

The store parameter will setup the environment to target UWPs. With that environment, I confirmed that the binaries do pass WACK, vcruntime140.dll is replaced by vcruntime140_app.dll and kernel32 is replaced by the proper API set import library.

**Comment by psled** [comment]
Awesome.

Confirming that now it works as expected.

Just a small typo in above command: `vcvarsall.bat`

Thank you for a quick help @khouzam .

**Comment by touseefbsb** [comment]
@psled  after running above command in command prompt , do we need to go through complete build process again or can we just make our app packages again in visual studio?

**Comment by psled** [comment]
Hi @touseefbsb,

I won't give you an up to date answer cause I haven't touched this library since then.

Although, as far as I'm concerned, above command is instructing currently opened command prompt to target UWP instead of desktop. After running it, you should probably run full build for FFmpeg library as well.

Moreover, you should probably repeat these steps separately for each architecture you would like to target (e.g. x64, x86, arm).

I remember that I also initially encountered some issue with ARM target but not sure what it was in the end. I have an ARM binary on my disk today so it has to worked for me somehow.

Just double check if you are using the right command prompt (there is now arm and arm64):

`C:\Program Files (x86)\Microsoft Visual Studio\2017\<Edition>\VC\Auxiliary\Build`

Also, do not forget that configure script for ARM is little bit different than the one for x64 and x86 (more on that [here](https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT))

**Comment by khouzam** [comment]
Hi @touseefbsb,

You should most likely run the command for ARM (ARM32). There are very few ARM64 Windows devices and those will usually also run ARM32 or x86.

All your FFmpeg binaries need to be build with the proper build settings, so you do need to recompile the FFmpeg binaries if they aren't build with the store stettings.

**Comment by HobbyLifeSoftware** [comment]
Thank you for this AMAZING fix!
