### ISSUE TITLE
Can't Get This to Build

### ISSUE THREAD

**Issue by seanocali** [Microsoft/FFmpegInterop#203]
I downloaded VS2015 and finally got ffmpeg built, but I can't get ffmpeginterop to build in vs2015 or vs2017.

> 1>------ Build started: Project: FFmpegInterop, Configuration: Debug x64 ------
1>pch.cpp
1>FFmpegInteropLogging.cpp
1>FFmpegInteropMSS.cpp
1>FFmpegReader.cpp
1>H264AVCSampleProvider.cpp
1>H264SampleProvider.cpp
1>MediaSampleProvider.cpp
1>c:\users\seano\desktop\ffmpeginterop-lukasf-alpha-support\ffmpeginterop\source\ffmpeginteropmss.cpp(68): error C4996: 'av_lockmgr_register': was declared deprecated
1>c:\users\seano\desktop\ffmpeginterop-lukasf-alpha-support\ffmpeg\build\windows10\x64\include\libavcodec\avcodec.h(5973): note: see declaration of 'av_lockmgr_register'
1>UncompressedAudioSampleProvider.cpp
1>UncompressedSampleProvider.cpp
1>UncompressedVideoSampleProvider.cpp
1>c:\users\seano\desktop\ffmpeginterop-lukasf-alpha-support\ffmpeginterop\source\uncompressedvideosampleprovider.cpp(112): error C4996: 'av_frame_get_best_effort_timestamp': was declared deprecated
1>c:\users\seano\desktop\ffmpeginterop-lukasf-alpha-support\ffmpeg\build\windows10\x64\include\libavutil\frame.h(587): note: see declaration of 'av_frame_get_best_effort_timestamp'
1>Done building project "FFmpegInterop.vcxproj" -- FAILED.
2>------ Build started: Project: MediaPlayerCPP, Configuration: Debug x64 ------
3>------ Build started: Project: MediaPlayerCS, Configuration: Debug x64 ------
4>------ Build started: Project: MediaPlayerJS, Configuration: Debug x64 ------
5>------ Build started: Project: UnitTest, Configuration: Debug x64 ------
5>CSC : error CS0006: Metadata file 'C:\Users\seano\Desktop\FFmpegInterop-lukasf-alpha-support\x64\Debug\FFmpegInterop\FFmpegInterop.winmd' could not be found
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(4277,5): error MSB3030: Could not copy the file "C:\Users\seano\Desktop\FFmpegInterop-lukasf-alpha-support\x64\Debug\FFmpegInterop\FFmpegInterop.winmd" because it was not found.
4>Done building project "MediaPlayerJS.jsproj" -- FAILED.
3>CSC : error CS0006: Metadata file 'C:\Users\seano\Desktop\FFmpegInterop-lukasf-alpha-support\x64\Debug\FFmpegInterop\FFmpegInterop.winmd' could not be found
2>pch.cpp
2>c:\users\seano\desktop\ffmpeginterop-lukasf-alpha-support\samples\sampleswin10\mediaplayercpp\pch.cpp : fatal error C1192: #using failed on 'C:\Users\seano\Desktop\FFmpegInterop-lukasf-alpha-support\x64\Debug\FFmpegInterop\FFmpegInterop.winmd'
2>        'The system cannot find the file specified.'
2>Done building project "MediaPlayerCPP.vcxproj" -- FAILED.
========== Build: 0 succeeded, 5 failed, 0 up-to-date, 0 skipped ==========

**Comment by seanocali** [comment]
I'm trying to build lukasf's alpha channel branch but I had the same errors when I tried the master branch. Prior to this I was just using the Nuget package.

**Comment by lukasf** [comment]
It looks like you are using a different ffmpeg version than the one that comes with FFmpegInterop. Did you update ffmpeg or use a build from a different branch? The ffmpeg version we currently use does not have a deprecation on av_lockmgr_register.

**Comment by lukasf** [comment]
If you want to use your custom ffmpeg build, you can add "4996" to the disabled warnings in the project's C++ compiler settings.

**Comment by seanocali** [comment]
I just used the latest FFmpeg master branch, the instructions on the FFmpeg Interop readme.md says to download the source from the FFmpeg repository.  I didn’t realize FFmpeg Interop came with its own specific FFmpeg source as I was just following those instructions.  Thanks.

**Comment by seanocali** [comment]
That fixed it, thanks again.

**Comment by mcosmin222** [comment]
We do not use the latest sources because these may have bugs. We usually bump up the version every 6 months or so.
