### ISSUE TITLE
COMException: Class not registered

### ISSUE THREAD

**Issue by seanocali** [Microsoft/FFmpegInterop#205]
Sorry to bother you guys again with this.  I'm sure it's just a matter of me not knowing what I'm doing, but I can't for the life of me get the assembly built from source code to work in my C# UWP project.

I built an FFMpegInterop x64 release, copied the winmd, dll, and the other 6 files to a libs folder in my C# project.  I added the winmd file as a reference and set copy local to true.  It builds and runs fine (using x64) but when I try it using it at runtime I get an exception at the FFmpegInteropMSS instantiation:

> System.TypeLoadException
>   HResult=0x80131522
>   Message=Requested Windows Runtime type 'FFmpegInterop.FFmpegInteropMSS' is not registered.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
>    at FFmpegInterop.FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri(String uri, Boolean forceAudioDecode, Boolean forceVideoDecode)
>    at TestingFFmpegInterop.MainPage.TestButton1_Tapped(Object sender, TappedRoutedEventArgs e) in C:\Users\seano\source\repos\TestingFFmpegInterop\TestingFFmpegInterop\MainPage.xaml.cs:line 36
> 
> Inner Exception 1:
> COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by mcosmin222** [comment]
You should also have a FFmpegInterop.dll in there, in addition to your av*.dll files.
The .winmd file cannot work without it.

**Comment by seanocali** [comment]
Thanks I

**Comment by seanocali** [comment]
I'll just use the project in my solution.

**Comment by seanocali** [comment]
I added the FFmpegInterop project, it built fine, I then added it as a reference to my main project.  Main project builds and runs fine.  At runtime I trigger a FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri and I get System.IO.FileNotFoundException: 'The specified module could not be found.

**Comment by seanocali** [comment]
Ok I got it working, I needed to put the ffmpeg build dlls in the root of my main project.  Sorry for not realizing the sample MediaPlayerCS project has it like that.  I assumed the FFmpegInterop dll had ffmpeg built into it.  There were no extra dlls that I recall when I used the FFmpegInterop Nuget package.

**Comment by mcosmin222** [comment]
Yes, the nugget has ffmpeg built in. But the project itself does not.

**Comment by reego-fr** [comment]
I can't remember what exactly, but there was a manual project edit needed to solve the "COMException: Class not registered" issue when referencing a winmd project built outside the current solution.
