### ISSUE TITLE
Build failed: Linker unable to open msvcrt.lib

### ISSUE THREAD

**Issue by webguydan** [Microsoft/FFmpegInterop#209]
Hi all!

Some env background:
Win10, MVSC 2017

Ran complete setup via the compilation guide, and confirmed MSYS2 shell setup via the listed commands. However, when running the build script for win10, I always get the following linker error (pasted from config.log)

fatal error LNK1104: cannot open file 'MSVCRT.lib'
C compiler test failed.

This is strange, because I can see the file it is looking for here:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\msvcrt.lib

env Paths also look correct, so it might be something else. Any help would be appreciated!

**Comment by lukasf** [comment]
The compilation guide and build scripts were made for Visual Studio 2015. You need to install VS2015 to successfully compile ffmpeg like that. If you only have VS2017 installed, then this explains your problems. @khouzam is working on a new build approach that will work with VS2017, but as I understand there are still some issues with that. See #136 #185

**Comment by webguydan** [comment]
Thanks a lot, I'll give that a try. Are there potential issues with having both 2015 and 2017 installed on the same box? (wrt compiling/setup of ffmpeg)

**Comment by lukasf** [comment]
No problem, I use that setup myself. You can use VS2017 to open and build the FFmpegInterop solution. But to compile ffmpeg, VS2015 must be installed as well.
