### ISSUE TITLE
How to change PlaybackRate

### ISSUE THREAD

**Issue by MengYunfan** [Microsoft/FFmpegInterop#221]
I set a MediaElement PlaybackRate=2.0, but it doesn't work.

**Comment by mcosmin222** [comment]
The library currently does not support this scenario. We can implement it but it will probably not get to be merged here since, but rather in our parallel fork.

**Comment by lukasf** [comment]
Please try setting MaxSupportedPlaybackRate on the MediaStreamSource like this:

              ```
      // Instantiate FFmpegInteropMSS using the opened local file stream
                    FFmpegMSS = await FFmpegInteropMSS.CreateFromStreamAsync(readStream, Config);
                    MediaStreamSource mss = FFmpegMSS.GetMediaStreamSource();

                    if (mss != null)
                    {
                        mss.MaxSupportedPlaybackRate = 4.0;

                        // Pass MediaStreamSource to Media Element
                        mediaElement.SetMediaStreamSource(mss);
```

It worked for me. Requires Windows 10 Creators Update or higher.

**Comment by MengYunfan** [comment]
@lukasf I retarget my project to 16299, but still not work.😂

**Comment by lukasf** [comment]
Glad to hear that!
