### ISSUE TITLE
[Question] How FFmpegInterop work with MediaPlayer & MediaPlaybackList & MediaBinder API in UWP app?

### ISSUE THREAD

**Issue by HppZ** [Microsoft/FFmpegInterop#232]

**Comment by khouzam** [comment]
Hi @HppZ 

FFmpegInterop provides a `MediaStreamSource` which can be used to instantiate a `MediaSource` using the `MediaSource::CreateFromMediaStreamSource` API. This will let you use FFmpegInterop with `MediaPlayer` and the other APIs that use a `MediaSource`.
