### ISSUE TITLE
fatal error LNK1120: 1 unresolved externals

### ISSUE THREAD

**Issue by xiedongweo** [Microsoft/FFmpegInterop#234]
I followed this [Instructions](https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT) to compile ffmpeg x64 for UWP, but I got the following error:

`BEGIN ./ffconf.jNjZgZMl.c
    1	int main(void){ return 0; }
END ./ffconf.jNjZgZMl.c
cl -nologo -MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00 -c -Fo./ffconf.HqaC4Hfy.o ./ffconf.jNjZgZMl.c
ffconf.jNjZgZMl.c
/d/Working_Space/GitHub/FFmpegInterop/ffmpeg/compat/windows/mslink -APPCONTAINER WindowsApp.lib -nologo -out:./ffconf.hSEPEeZV.exe ./ffconf.HqaC4Hfy.o
LINK : error LNK2001: unresolved external symbol _mainCRTStartup
C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x64\WindowsApp.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\lib\store\amd64\MSVCRT.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'X86'
./ffconf.hSEPEeZV.exe : fatal error LNK1120: 1 unresolved externals
C compiler test failed.`

Could anyone help me on this issue?

**Comment by mcosmin222** [comment]
Try reinstalling Visual Studio 2015.

**Comment by xiedongweo** [comment]
@mcosmin222  Are you sure that my Visual Studio 2015 has some problems? Reinstalling VS is not easy for me.

**Comment by mcosmin222** [comment]
I encountered the "C compiler test failed" error in 2 instances:

1) Incorrectly configured VS command prompt environment for the target platform (i.e, use the x64 config for ARM for example).
2) Something conflicting within VS setups, this usually happens if VS itself is corrupted or if several versions of VS are installed.

**Comment by mcosmin222** [comment]
Sadly, no. Perhaps @khouzam can help more

**Comment by khouzam** [comment]
Hi @xiedongweo 

Can you verify which Developer Command Prompt shortcut you are using?

Also, can you try from a plain command prompt to run buildFFmpeg.bat from the FFmpepInterop repo? This should setup your environment correctly for the architectures you specify.
