### ISSUE TITLE
FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri returns null on Windows Phone 8.1

### ISSUE THREAD

**Issue by senkia** [Microsoft/FFmpegInterop#29]
When I use the FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri method to play a remote file or RTSP stream it returns null on Windows Phone 8.1. I found out that in the FFmpegInteropMSS::CreateMediaStreamSource method, the avformat_open_input call returns an error code -9 and that causes the failiure but I dont know what that code means. When I try to do the same on Windows 8.1 the file or RTSP stream opens up without any error.

**Comment by timotiusmargo** [comment]
Did you call the method from the Windows Phone 8.1 emulator (x86) instead of device (ARM)? There's a potential access or capabilities issue in the emulator that we can look at. But the device should be able to open it without any issue.

**Comment by senkia** [comment]
Yes I've tried it on the emulator, I also get a few of these handled exceptions:
First-chance exception at 0x7789210B in MediaPlayerCS.WindowsPhone.exe: Microsoft C++ exception: Cn::XH at memory location 0x03D8ED78.
Right after the launch of the application before I even set the mediaelement's source.

**Comment by senkia** [comment]
I've just checked it on an actual device and the rtsp stream plays fine although it takes quite a while before it starts playing and there's a huge delay (almost half a minute in my case).

**Comment by timotiusmargo** [comment]
Thanks for the update @senkia. Reducing MediaStreamSource BufferTime may reduce the delay at the cost of playback stability (increasing possible chance for buffering during playback). The default value is 3 seconds, so it might be something else that causes longer delay. We will also add a feature to pass in FFmpeg options to enable us to tweak even more.
