### ISSUE TITLE
Latest version of ffmpeg certification issues

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#39]
I get the following errors from the certification kit tests

This API is not supported for this application type - Api=avcodec_is_open. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avcodec_open2. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avcodec_pix_fmt_to_codec_tag. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avcodec_register_all. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avcodec_string. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpicture_get_size. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_aac_parse_header. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_ac3_channel_layout_tab. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_ac3_parse_header2. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_align_put_bits. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_bprint_to_extradata. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_copy_bits. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_copy_pce_data. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_dca_convert_bitstream. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_dca_sample_rates. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_dirac_parse_sequence_header. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_dnxhd_get_frame_size. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_dnxhd_get_interlaced. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_exif_decode_ifd. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_find_pix_fmt. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_find_start_code. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_get_raw_pix_fmt_tags. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_h264_has_num_reorder_frames. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_bits_ac_chrominance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_bits_ac_luminance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_bits_dc_chrominance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_bits_dc_luminance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_val_ac_chrominance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_val_ac_luminance. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mjpeg_val_dc. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpa_bitrate_tab. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpa_decode_header. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpa_freq_tab. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpeg4audio_get_config. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpeg4audio_sample_rates. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_mpegaudio_decode_header. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_pix_fmt_bps_avi. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_pix_fmt_bps_mov. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_split_xiph_headers. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_tak_parse_streaminfo. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=avpriv_toupper4. Module=avcodec-57.dll. File=avformat-57.dll.
This API is not supported for this application type - Api=av_get_pcm_codec. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=av_init_packet. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=av_new_packet. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=av_packet_new_side_data. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=av_packet_unref. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=avpicture_get_size. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=avpicture_layout. Module=avcodec-57.dll. File=avdevice-57.dll.
This API is not supported for this application type - Api=av_free_packet. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=av_init_packet. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=avcodec_close. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=avcodec_decode_audio4. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=avcodec_decode_video2. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=avcodec_flush_buffers. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.
This API is not supported for this application type - Api=avcodec_open2. Module=avcodec-57.dll. File=ffmpegWindowsPhone.dll.

**Comment by timotiusmargo** [comment]
Which platform are you targeting and build against? Could you please provide the App Certification Kit version as well?

**Comment by mcosmin222** [comment]
App certification kit version is 10.0

Target platform is WP8.1 ARM.
