### ISSUE TITLE
avutil dll will fail certification because Sleep() is not supported in Windows Phone 8.1

### ISSUE THREAD

**Issue by n4spd** [Microsoft/FFmpegInterop#4]
The supported APIs test detected the following errors:
- This API is not supported for this application type - Api=Sleep. Module=api-ms-win-core-synch-11-2-0.dll. File=avutil-xx.dll.

**Comment by timotiusmargo** [comment]
Did you build avutil-xx.dll using the instructions below?
https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT

If so, could you share the FFmpeg revision you are at along with all configure options you use?

**Comment by n4spd** [comment]
1. yes.  I used the instructions for "Windows Phone 8.1 ARM" from https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT

2. RELEASE file says "2.5.git"

3. note: code will pass msvc certification test but once app is submitted, MS periodic scans will catch the Sleep() call and send you an email about the invalid api usage (maybe my desktop msvc cert test app is outdated).

4. I used the configure params from the "Windows Phone 8.1 ARM" instruction (see answer#1).  My configure.mak file starts with:
# Automatically generated by configure - do not modify!
ifndef FFMPEG_CONFIG_MAK
FFMPEG_CONFIG_MAK=1
FFMPEG_CONFIGURATION=--toolchain=msvc --disable-programs --disable-dxva2 --disable-asm --arch=arm --as=armasm --cpu=armv7 --enable-thumb --enable-shared --enable-cross-compile --target-os=win32 --extra-cflags='-MD -DWINAPI_FAMILY=WINAPI_FAMILY_PHONE_APP -D_WIN32_WINNT=0x0603 -D__ARM_PCS_VFP' --extra-ldflags='//appcontainer -MACHINE:ARM -subsystem:console -opt:ref WindowsPhoneCore.lib RuntimeObject.lib PhoneAppModelHost.lib -NODEFAULTLIB:kernel32.lib -NODEFAULTLIB:ole32.lib' --prefix=Build/WindowsPhone81/ARM --disable-doc --disable-ffplay --disable-ffserver --disable-ffmpeg --disable-postproc --disable-avfilter --disable-avdevice --disable-encoders --disable-hwaccels --disable-indevs --disable-outdevs --disable-devices --disable-filters --disable-bzlib --disable-pthreads --disable-debug --enable-decoder=mjpeg --enable-decoder=h264 --enable-decoder=mp3 --enable-decoder=mp2 --enable-decoder=mpegaudio --enable-parser=h264 --enable-parser=mpegaudio --enable-demuxer=h264 --enable-demuxer=rtsp --enable-demuxer=rtp --enable-protocol=rtsp --enable-protocol=rtp --enable-protocol=udp --enable-protocol=tcp --enable-protocol=http
prefix=Build/WindowsPhone81/ARM
LIBDIR=$(DESTDIR)${prefix}/lib
SHLIBDIR=$(DESTDIR)${prefix}/bin
INCDIR=$(DESTDIR)${prefix}/include
BINDIR=$(DESTDIR)${prefix}/bin
DATADIR=$(DESTDIR)${prefix}/share/ffmpeg
DOCDIR=$(DESTDIR)${prefix}/share/doc/ffmpeg
MANDIR=$(DESTDIR)${prefix}/share/man

Hope that helps,
Thanks, Rob

**Comment by mcosmin222** [comment]
I didn't manage to get past the desktop certification. All ffmpeg dlls fail.

:◦File avcodec-56.dll has failed the AppContainerCheck check.
◦File avdevice-56.dll has failed the AppContainerCheck check.
◦File avfilter-5.dll has failed the AppContainerCheck check.
◦File avformat-56.dll has failed the AppContainerCheck check.
◦File avutil-54.dll has failed the AppContainerCheck check.
◦File swresample-1.dll has failed the AppContainerCheck check.
◦File swscale-3.dll has failed the AppContainerCheck check.

**Comment by qyljcy** [comment]
You cannot use desktop dll directly.
If you want, you can try my fork https://github.com/qyljcy/FFmpeg. It's based on ffmpeg 2.4 and all dlls can past WACK

**Comment by timotiusmargo** [comment]
The linker flag -APPCONTAINER is missing from the compilation guide. You can simply append --extra-ldflags with -APPCONTAINER and rebuild the libraries and apps to fix it. The compilation guide is currently being updated to address the issue.

**Comment by timotiusmargo** [comment]
@Rob (n4spd): Your config seems to have appcontainer linker flag but it may be ignored since it is prefixed with slash (/) instead of dash (-). I.e.

--extra-ldflags='-appcontainer

instead of

--extra-ldflags='//appcontainer

This is possibly ignored during build and the config.log may warn you about it.

Apart from that, you mentioned that this app package passed the Windows App Certification Kit but somehow rejected from the submission. Can you share the Windows App Certification Kit version? Meanwhile could you try the change recommended above?

**Comment by mcosmin222** [comment]
Ups, forgot to mention i fixed it soon after that post :P

**Comment by timotiusmargo** [comment]
The https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT build instruction has been updated to ensure it builds fine with the latest revision and pass the Windows App Certification Kit.

@n4spd: Are you still having the certification issue?

**Comment by n4spd** [comment]
1. I am using Windows App Certification Kit 3.4.   Again, WACK 3.4 passes fine, NO AppContainerCheck error or no error about Sleep() usage not available in Phone 8.1 universal app.

2. will change to -appcontainer for next release and see if that helps. 

3. it's only after 1-2 weeks that I got an email about the Sleep API usage not available on phone 8.1.  The function av_usleep() in file time.c in libavutil calls Sleep() which is not available in windows phone 8.1 universal app.

thx rob

**Comment by qyljcy** [comment]
Hi @n4spd, you can try my ffmpeg fork. I have used winrt api instead of sleep().
https://github.com/qyljcy/FFmpeg
Just run the script and take a coffee, hope you can enjoy it.

**Comment by timotiusmargo** [comment]
Thanks for the update Rob (n4spd). Let me know if you still have any problem after adapting the -appcontainer LD flag.
