### ISSUE TITLE
Opus playback

### ISSUE THREAD

**Issue by brabebhin** [microsoft/FFmpegInterop#42]
Has anyone managed to play opus files with this project?

I always get a division by zero in the opus decoder on ffmpeg's part. I googled around a bit and noticed nobody seems to be having this issue. My _other_ opus decoder players the file just fine.

Maybe there is an issue in this particular port?

**Comment by reego-fr** [comment]
Hi,

I am able to play the sample opus files found on this site : http://xiph.org/~giles/2012/opus/
http://xiph.org/~giles/2012/opus/detodos.opus 
Don't you ?

**Comment by mcosmin222** [comment]
download and install this http://sourceforge.net/projects/taudioconverter/?source=typ_redirect

pick any music file you want, convert it to opus.
Feed it to the ffmpeg interop project > not working. 

My app has 1 other opus codec (direct port of opus lib to winRT). That codec will play your file newly converted opus just fine.

**Comment by reego-fr** [comment]
I read ffmpeg is using a native decoder for opus unless it is configured to use libopus. Given the error you get there might be an issue with it. 
It would be interesting to see if ffplay fails to read such files when built without libopus.

**Comment by reego-fr** [comment]
As a side note, I transcoded a short file with the lastest TaudioConverter and it played well using the current FFmpegInterop projet samples.

**Comment by mcosmin222** [comment]
I tried that but the instructions on how to actually integrate opuslib in ffmpeg aren;t exactly clear
