### ISSUE TITLE
Cannot Include .dll 

### ISSUE THREAD

**Issue by wisien92** [Microsoft/FFmpegInterop#46]
Hi,

I want to built FFmpegInterop.WindowsPhone c++ library and when I try to include built .dll to different project I get message:

" A refference to (...) could not be added. Please make sure that file is accessible and that it is a valid assembly or COM component".

**Comment by wisien92** [comment]
And when I add existing project to project in different place I get errors while building 

 Cannot open include file: 'libavformat/avformat.h': No such file or directory  (...)

**Comment by reego-fr** [comment]
Hi,

there are required manual changes to apply to your project and app package manifest in order to include the dll correctly. It happens with other projects as well. 
I don't remember the details but you may find helpful information here: https://github.com/Microsoft/FFmpegInterop/issues/11
