### ISSUE TITLE
How to use in WP8.1 Silverlight?

### ISSUE THREAD

**Issue by iamstudentVN** [Microsoft/FFmpegInterop#5]
I try import in project Silverlight but it not support  Windows.Media.Core MediaStreamSource

**Comment by qyljcy** [comment]
This project is based on WinRT, not Silverlight.

**Comment by khouzam** [comment]
While Silverlight does support its own version of a MediaStreamSource, it does not support the model that FFmpegInterop is using. It is possible to write a MediaStreamSource for Silverlight using similar code to what FFmpegInterop is doing. The main difference is that the MediaStreamSource would be written in C# and you would need to write a WinRT C++ component to provide the interop layer with FFmpeg.
