### ISSUE TITLE
Get thumbnail/snapshot from stream

### ISSUE THREAD

**Issue by wisien92** [Microsoft/FFmpegInterop#51]
Is it possible to extract single frame from stream via method??

**Comment by wisien92** [comment]
Or you could maybe help me and tell how to achieve this (if you know)

**Comment by wisien92** [comment]
Or would you help me writting method for FFmpegInteropMSS class called 'GetThumbnailForStream' that would connect to stream and returned firt frame as bitmap? I am not sure where to start and help would be apprecieated

**Comment by wisien92** [comment]
I have found something;

in MediaSampleProvider in method WriteAVPacketToStream there is line 

auto aBuffer = ref new Platform::Array<uint8_t>(avPacket->data, avPacket->size);

and I belive that this is the place that stores single frame data that is needed to convert into bitmap - now since I do not know c++ too much I have a question : how can I convert it into a form that I could return via public method ?

**Comment by krishnan-unni** [comment]
Hi I am not an expert in c++. But what I do know is when you are doing a winrt component you can return the WinRT types only and that would be converted to a .NET general type in the managed code. In your case you can return a Array<byte>^ maybe. In the managed code this would be represented as byte[] . For more info refer : https://msdn.microsoft.com/en-us/library/br230301.aspx#PassingToManaged

**Comment by wisien92** [comment]
You're right. Right now I have passed empty array of Bytes to FFmpegInteropMsss and from there passed to C# project - and it worked. Now I need to make appropriate projection and then I'll write/edit if it worked (but no time today :( );

**Comment by krishnan-unni** [comment]
Alright looking forward to it. Let me know if you have compiled ffmpeg with libx264 in win 10. I am looking for some guidance there.

**Comment by wisien92** [comment]
Unfortunetly someone cross-comiled the libraries and send it to me so I cannot be of much help.

I am having struggle - I try to use OutputDebugString(L"TEST"); but nothing is displayed in Debug window, and when setting breakpoints I get information that symbols were not loaded - does anyone know how to debug c++ library while running c# project?

**Comment by krishnan-unni** [comment]
To enable native debugging in c# projects, go to the project properties. There in debugging you'll see that the drop-down is selected as managed. Change it to mixed managed and native. You still be able to hit your breakpoints now in c++ code and se what's going on.

**Comment by krishnan-unni** [comment]
One more thing, the vross compiled library that you have for ffmpeg includes libc264? If yes, is it for win 10 x64? I yes could you please share it?

**Comment by wisien92** [comment]
I am not sure if the file I uploaded containes the proper ffmpeg build (for your needs).

As for the problem in MediaStream in event SampleRequested I can obtain data in YUV format -> then I have written converter based on code https://gist.github.com/fzakaria/2472889 (in python but the algorith is the same , look for 2xfor loops). I now have image saved in pictures folder! 

[ffmpeg_ARM_Win10_56.zip](https://github.com/Microsoft/FFmpegInterop/files/91858/ffmpeg_ARM_Win10_56.zip)

**Comment by senkia** [comment]
Hi,
Could you share this converter with us? I cant seem to get the yuv converters working that I've found. 
Thanks.

**Comment by wisien92** [comment]
This is the code that worked for me

                int width = //ImageWidth
                int heigth = //ImageHeigth

                int frameSize = width * heigth;

                int y, u, v, r, g, b;

                byte[] yvuArray = sample.ToArray(); //sample us if type IBuffer
                byte[] bitmapArray = new byte[width * heigth * 4];

                for (int j = 0; j < heigth; j++)
                {
                    for (int i = 0; i < width; i++)
                    {
                        y = yvuArray[Convert.ToUInt32((j * width + i))];
                        y = y < 16 ? 16 : y;
                        u = yvuArray[Convert.ToUInt32(frameSize + (j >> 1) * width + (i & ~1) + 0)];
                        v = yvuArray[Convert.ToUInt32(frameSize + (j >> 1) * width + (i & ~1) + 1)];

                        b = (int)(1.164 * (y - 16) + 2.018 * (u - 128));
                        g = (int)(1.164 * (y - 16) - 0.813 * (v - 128) - 0.391 * (u - 128));
                        r = (int)(1.164 * (y - 16) + 1.596 * (v - 128));

                        r = r < 0 ? 0 : (r > 255 ? 255 : r);
                        g = g < 0 ? 0 : (g > 255 ? 255 : g);
                        b = b < 0 ? 0 : (b > 255 ? 255 : b);

                        int indexJump = (j * width + i) * 4;

                        bitmapArray[indexJump] = (byte)r;
                        bitmapArray[indexJump + 1] = (byte)g;
                        bitmapArray[indexJump + 2] = (byte)b;
                        bitmapArray[indexJump + 3] = 0x00;
                    }
                }
