### ISSUE TITLE
Question: Cannot open include files

### ISSUE THREAD

**Issue by JeFrederick** [Microsoft/FFmpegInterop#66]
I followed the compile directions and everything seems to have worked. I can open the sample media player solution and the ffmpegInterop project will build with no errors. When I try adding the project to the application I'm working on though it gives several errors such as Cannot open include file: 'libavformat/avformat.h'. I've looked at the addition library and additional include properties and don't see anything obviously wrong, and any changes I've made haven't changed the errors either. Any suggestions on where I am making a mistake?

**Comment by timotiusmargo** [comment]
Hi @JeFrederick,

If I get you correctly, you built and deploy the **FFmpeg** libraries, **FFmpegInterop** project, ran the sample without any issue, and now you are trying to add the **FFmpegInterop** project to your application project. It sounds like the **FFmpegInterop** project loses the path to the **FFmpeg** header files folder e.g.
`C:\ffmpeg\Build\Windows10\x86\Include`

Can you see where the `[FFmpegInterop.vcxproj](https://github.com/Microsoft/FFmpegInterop/blob/master/FFmpegInterop/Win10/FFmpegInterop/FFmpegInterop.vcxproj)` **AdditionalIncludeDirectories** point to?

This can be accessed through `Visual Studio > FFmpegInterop Project > Properties > General > C/C++ > Additional Include Directories`

When you edit the entry, you can see the exact path it is map into in the **Evaluated Value** window. The evaluated path is where your **FFmpeg** headers should be in.

**Comment by JeFrederick** [comment]
Thanks for the help, that was the problem. There was one folder that was missing in the path. It's building properly now.
