### ISSUE TITLE
ffmpeg compilation error in windows 10 x64 for Visual Studio 2015 CE

### ISSUE THREAD

**Issue by Anqush** [Microsoft/FFmpegInterop#68]
Hello guys,
So i was trying to  use FFmpegInterop for win10 UWP application. And followed the specification given on https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT. 

here is some environment information:
VS2015 Community Edition with 10.0.10240.0 SDK
OS: Windows 10 Enterprise x64
PATH were set to:Program Files (x86)/Microsoft Visual Studio 14.0/VC/BIN/x64_ARM

So when i did this in msys2_shell.bat

../../../configure \
--toolchain=msvc \
--disable-programs \
--disable-d3d11va \
--disable-dxva2 \
--arch=x86_64 \
--enable-shared \
--enable-cross-compile \
--target-os=win32 \
--extra-cflags="-MD -DWINAPI_FAMILY=WINAPI_FAMILY_APP -D_WIN32_WINNT=0x0A00" \
--extra-ldflags="-APPCONTAINER WindowsApp.lib" \
--prefix=../../../Build/Windows10/x64

I got a warning regarding some pkg file that can't be found and may cause library detection issues.

For then i ignored it. After that i entered 

make

this started a series of processing in which there is a lot of possibly harmful warnings. Like:-

c:\ffmpeginterop\ffmpeg\libavcodec\get_bits.h(307): warning C4101: 're_cache': unreferenced local variable
CC      libavformat/srtdec.o
srtdec.c
c:\ffmpeginterop\ffmpeg\libavutil\libm.h(438): warning C4211: nonstandard extension used: redefined extern to static
c:\ffmpeginterop\ffmpeg\libavformat\subtitles.h(189): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data

**So my question is that. Is this dangerous to proceed with. Can you help me for i should proceed with my project without any worry or not? And i would be gratefull if anyone can guide me to watc out for specific errors that this could generate.**

I know this is a lot to ask. But i would be gratefull.
Thanks

**Comment by reego-fr** [comment]
Hi,
did you get the dll files in the end ?
Honestly, I didn't pay much attention to these warnings but the ones you provided do not look harmful to me and should not cause errors here. 
If I am wrong, your app may crash but it is not the end of the world !
Please take my answer with caution, I am not specialist !

**Comment by Anqush** [comment]
Thanks for response.
But I cant compile the ffmpeginterop project now. it says the project is outdated. what should i do now.

Thanks again

**Comment by khouzam** [comment]
Can you expand on the error message that you're seeing? What is outdated?

**Comment by reego-fr** [comment]
Hi,
I was talking about ffmpeg dlls, not the ffmpeginterop project. The dlls created as part the of compilation process described at https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT are required by the ffmpeginterop project. The later will not build without these (it must be why VS says the project is outdated, it was never built). 

1. Check that "make" an "make install" created dlls, check the path were they were copied to. It will be something like Build/Windows...
2. In Visual Studio, check the ffmpeginterop solution platforms drop down (or go to the Build tab > Configuration manager). Make sure the selected entry (active platform) matches the platform you built ffmpeg for (x64, arm, ...). 

Hope this helps.

**Comment by Anqush** [comment]
Thanks reego-fr,

That worked just fine.
The 2nd step was the cause for error on ffmpeginterop project build.

So for now i would ignore the errors in the make of ffmpeg and would keep an eye on the project for any crashes. 

Thanks a lot again.
