### ISSUE TITLE
UDP stream hang

### ISSUE THREAD

**Issue by maxstee** [Microsoft/FFmpegInterop#69]
Hi,

I'm trying to read an plain udp stream from localhost. The stream works with ffplay and vlc, but the sample "MediaPlayerCS"  just hangs when insert the uri. It works well reading local files and rtsp streams, just plain udp and udp rdp streams hang.
I checked "private networks" in manifest and  "Allow local network loopback" in project properties.
I tried compiling the last 2.8 branch and the same 2.7.1 ffmpeg branch linked in the project with same results.
I ran successfully all the tests in UnitTest. 
![test](https://cloud.githubusercontent.com/assets/18459512/14523732/849c2022-0235-11e6-80bb-6e859c1a4a8b.png)
While debugging, it just hangs on 
`if (avformat_open_input(&avFormatCtx, charStr, NULL, &avDict) < 0)`
at line 159 of FFmpegInteropMSS.cpp.
The method simply never returns.

What can i do to debug it better?
Thanks.

**Comment by reego-fr** [comment]
Hi,
did you check "Internet (Client & Server)" in your app's manifest ?

**Comment by maxstee** [comment]
@reego-fr Yes, I found out that local networks with 10.* IPs need "internet Client & server" to work.

I was trying trasmit udp stream from localhost with vlc, and it simply does not work. Loopback works with rtsp but not with rtp-udp and plain udp. Maybe it's a limitation of the "allow local network loopback" flag.

I resolved just trasmitting from another pc.

**Comment by qian256** [comment]
Hi @maxstee ,
I experienced the same issue: rtp-udp is not working, even from another PC. I load the SDP file in the app. The SDP is successfully parsed, but no actual package go through. Do you have any suggestion about this issue?
Thanks!
