### ISSUE TITLE
Question on using with Media Foundation

### ISSUE THREAD

**Issue by proludio** [Microsoft/FFmpegInterop#7]
Can this be used in an exiting application written for Media Foundation?
Specifically the decoders / encoders?

**Comment by khouzam** [comment]
Yes it is very possible to integrate this with an existing application that is using MediaFoundation. The FFmpegInterop object creates a MediaStreamSource which implements the IMFMediaSource interface and can be connected to the MediaFoundation graph. This will allow to leverage the container format processors from FFmpeg as well as the decoders if you want. At this point, FFmpegInterop is a playback component and therefore would not be usable to get to the encoders, but it is certainly something that can be done in the future.
