### ISSUE TITLE
FFmpeg libs failing WACK test

### ISSUE THREAD

**Issue by abhilashca** [Microsoft/FFmpegInterop#79]
Hello experts,

I have UWP application that uses FFmpegInterop libs. I have created the libs as mentioned in the [compilation instruction for WinRT](https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT). However, my app always fails WACK test.
Below is the error I am getting in WACK test report:

------------------------

•Error Found: The supported APIs test detected the following errors:

API swr_alloc_set_opts in swresample-1.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API swr_convert in swresample-1.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API swr_free in swresample-1.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API swr_init in swresample-1.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API sws_getContext in swscale-3.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API sws_scale in swscale-3.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_dict_free in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_dict_set in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_frame_alloc in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_frame_get_best_effort_timestamp in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_frame_unref in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_free in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_freep in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_get_bytes_per_sample in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_get_default_channel_layout in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_image_alloc in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_malloc in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_samples_alloc in avutil-54.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_free_packet in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_init_packet in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avcodec_close in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avcodec_decode_audio4 in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avcodec_decode_video2 in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avcodec_flush_buffers in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avcodec_open2 in avcodec-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_find_best_stream in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_read_frame in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_register_all in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API av_seek_frame in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avformat_alloc_context in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avformat_close_input in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avformat_find_stream_info in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avformat_open_input in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.
◦API avio_alloc_context in avformat-56.dll is not supported for this application type. FFmpegInterop.dll calls this API.

•Impact if not fixed:  Using an API that is not part of the Windows SDK for Windows Store apps violates the Windows Store certification requirements. 

------------------------

Please note, I even tried creating assemblies via BuildFFmpeg.bat but that too fails WACK test. I am creating the assemblies with latest ffmpeg and ffmpeginterop code from GitHub.
Any idea why it's so?

Thanks.

**Comment by khouzam** [comment]
Hi @abhilashca,

I can reproduce the issue with the ffmpeg3.0.1 branch but not the master branch.

Is that the branch that you are using?

**Comment by abhilashca** [comment]
I took the v3.0.1 and had the issue,
I deleted everything, started over with master branch.
Now it builds fine.
Thanks.
