### ISSUE TITLE
CreateFFmpegInteropMSSFromUri and m3u8

### ISSUE THREAD

**Issue by MeSaNei** [Microsoft/FFmpegInterop#8]
Hi,
I'm trying to play videos from m3u8 that responded by Twitch.

The url looks like this(VLC plays it perfectly):
http://video60.fra01.hls.ttvnw.net/hls-826cd8/pibadi_14836053520_256300529/high/py-index-live.m3u8?token=id=111164763824255259,bid=14836053520,exp=1434221194,node=video60-1.fra01.hls.justin.tv,nname=video60.fra01,fmt=high&sig=01d45ffcdb2da2a12f2d43b867b2b1f8262cc0c4

But I when I try:

public async Task<MediaStreamSource> GetMediaSource(string videoStream)
        {            
            FFmpegMSS = FFmpegInteropMSS.CreateFFmpegInteropMSSFromUri(videoStream, false, false);
           ........
            var result = FFmpegMSS.GetMediaStreamSource();
            return result;
        }
FFmpegMSS is null after processing.

Also should FFmpegInterop support m3u8 playlist?

Thank you.

**Comment by khouzam** [comment]
This is not a stupid question at all. I have just tried a random m3u8 stream and it does seem to work, although it takes a while for the stream to start playing. Feel free to open an issue to track problems that you might be having.
