### ISSUE TITLE
Complying with LGPL license in Windows Store app

### ISSUE THREAD

**Issue by Romasz** [Microsoft/FFmpegInterop#95]
Hi guys, thanks for great work you have done. I have some doubts regarding publishing the app with FFmpeg and FFmpegInterop in the Windows Store. [At the blog from Windows App Team](https://blogs.windows.com/buildingapps/2015/06/05/using-ffmpeg-in-windows-applications/#gDPSWOZCgcL4zsMo.97) it's said that: 'After following the compilation instructions, developers can include FFmpeg libraries in their applications...', however [FFmpeg compliance checklist](https://www.ffmpeg.org/legal.html) states that we should use dynamic linking. 

Technically we put dll's inside the package, but user won't be able to get to them for example to echange them (at least without jailbraking the device) - here are my doubts if it's okay with the license. 

Anyway I'm still confused what should I do to comply with the license of FFmpeg (LGPL) and FFmpegInterop (ASF), when I put them in my project, let's say without any changes. Is there any help I can get with this?

**Comment by khouzam** [comment]
Hi @Romasz 

This really touches on legal interpretations of the LGPL license, so you should consult a lawyer for proper legal advice. The GNU website is a pretty good website for giving some answers on this part (see https://www.gnu.org/licenses/gpl-faq.html).  My general understanding is that the source code availability requirements apply strictly to the library and that you should not interfere with users’ modification rights under the LGPL in your component and that would generally  not require you to allow for the replacement of any of the components within the application. But again, I am not a lawyer and I recommend consulting one for proper legal advice.

Thanks

**Comment by Romasz** [comment]
Hi @khouzam  

Thanks for the answer ad your work. Yeah, everything depends on interpretation here, it will also probably depend on the lawyer you ask. As my app is rather a small one and lawyers can cost a lot of money (from my experience they will also give opinions and interpretations rather than solution :) ), I will leave the app as it is. 

Have a nice day!

**Comment by mcosmin222** [comment]
The license applies only to the FFmpeg code. In our case, unless you went hardcore and modified it, or used any of the source code outside of FFmpeg dlls, there is no need to distribute anything, since we are using the readily available FFmpeg from their official website.

All you need to do is mention the program uses FFmpeg.

**Comment by Romasz** [comment]
@mcosmin222 Thanks for reply. As for now I don't need a hardcode mode with modyfing FFmpeg nor use the code elswere. Therefore it will probably end as you have mentioned, information, links and license.
